### ISSUE TITLE
Upload failed, but says "total success"

### ISSUE THREAD

**Issue by meirion** [ylexus/jiotty-photos-uploader#50] opened 2020-07-04 19:24 UTC
Firstly. thanks for this, seems like it could be incredibly useful!
Unfortunately I can't get it to work on a small set of test images...

![image](https://user-images.githubusercontent.com/324459/86519616-544b0180-be34-11ea-9d16-604753dc887c.png)

![image](https://user-images.githubusercontent.com/324459/86519626-5f059680-be34-11ea-97c7-27e02dfc3331.png)

**Comment by meirion** [comment] 2020-07-04 19:26
My mistake, I poked around and found out I could click on 'Failures' to get more details. turned out my photos storage was maxed out.

![image](https://user-images.githubusercontent.com/324459/86519665-af7cf400-be34-11ea-8e9c-30d97d9e3f0b.png)


Perhaps 'Failures' could look more clickable?

**Comment by meirion** [comment] 2020-07-04 19:30
tried again on another account with space available, this time got an error about needing a valid upload token.

![image](https://user-images.githubusercontent.com/324459/86519690-29ad7880-be35-11ea-9c0e-57bc1bc95362.png)

**Comment by ylexus** [comment] 2020-07-04 20:15
Interesting, can you please zip and attach here the contents of “~/.jiottyphotosuploader/logs” and “~/.jiottyphotosuploader/data.json” after you’ve reproduced the problem?

**Comment by ylexus** [comment] 2020-07-04 20:18
> My mistake, I poked around and found out I could click on 'Failures' to get more details. turned out my photos storage was maxed out.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/324459/86519665-af7cf400-be34-11ea-8e9c-30d97d9e3f0b.png)
> 
> 
> 
> 
> 
> Perhaps 'Failures' could look more clickable?

Yes I’ll see if I can decorate it to look more like a link.

**Comment by ylexus** [comment] 2020-07-05 14:04
I think I know why it happened. Jiotty remembers upload tokens for files you previously tried to upload, not to re-upload them again. However, when you log out and log in as another google user, those upload tokens are no longer valid. In fact, the whole upload state needs to be invalidated on logout. I’ll fix this.

**Comment by ylexus** [comment] 2020-07-05 14:10
@wheleph just in case you’d still want to contribute this one is quite simple. A css change to make links look more like links (underline) and also remove more files on logout (it already removes credentials, just need to also delete data.json).

**Comment by ylexus** [comment] 2020-07-05 23:16
> @wheleph just in case you’d still want to contribute this one is quite simple. A css change to make links look more like links (underline) and also remove more files on logout (it already removes credentials, just need to also delete data.json).

Actually, It’s a bit more involved, sorry. I’ve started working on it today.

**Comment by meirion** [comment] 2020-07-06 11:05
[Archive.zip](https://github.com/ylexus/jiotty-photos-uploader/files/4878463/Archive.zip)
Sure, here are the files you need.
Let me know when I can try the app again :)

**Comment by ylexus** [comment] 2020-07-06 12:20
> [Archive.zip](https://github.com/ylexus/jiotty-photos-uploader/files/4878463/Archive.zip)
> 
> Sure, here are the files you need.
> 
> Let me know when I can try the app again :)

Thanks. Can you quit the app, delete data.json and then launch the app and try again? If it works this time, then this confirms why I think it fails. It should also fix the problem for you.

**Comment by meirion** [comment] 2020-07-06 13:56
OK I deleted the app and emptied the ~/.jiotty... folder
Reinstalled the app, logged in with the correct google account and tried the same test folder of images.
Got different errors this time:

![image](https://user-images.githubusercontent.com/324459/86600664-42826f00-bf98-11ea-819d-10633a2ad91f.png)

New log files
[Archive.zip](https://github.com/ylexus/jiotty-photos-uploader/files/4879318/Archive.zip)

**Comment by ylexus** [comment] 2020-07-06 15:58
Looks like this time you hit an existing limitation where you are trying to re-upload a photo that's been uploaded manually, or via a different app. It was actually previously possible to do it, but I made it worse later, see #49  
To check this is the issue, can you tell me what Google Photos web shows when you click on the information (i) icon on this photo https://photos.google.com/lr/photo/ANo0wPyc2v9-sQO04sO_wPaM8CIvhpXKkowDslXRcjeXDQlUQq2DjpBdp9fS3WwAUtj2v5uyjV9-4HG77tnhY6JNlyNXv4yEgQ (with the file name IMG_20200704_151559.jpg") - does it say "Uploaded from Jiotty Photos Uploader" like on the screenshot below? If it doesn't, it's an externally uploaded photo and Jiotty would skip it with the error on your screenshot and won't add it to any albums. After this issue, I'll work on #49 which will basically allow you to choose between supporting already-uploaded photos (which  guess is what you'd want here) and order of items in the album. Unfortunately, I can't make both work at the same time doe to API limitations.

<img width="307" alt="Screenshot 2020-07-06 at 16 54 40" src="https://user-images.githubusercontent.com/6009806/86613452-8631a480-bfa9-11ea-87ee-dafdc1bb0b6c.png">

**Comment by ylexus** [comment] 2020-07-06 16:46
@axylee can I please ask you to translate the following line in all Chinese resources, like before? Please leave %s placeholder - it will display the value of "progressBoxFailuresHyperlinkText" resource, for example, 错误:
`uploadPaneLogAreaPartialSuccessLabel=Done with some failures, to review click on "%s" links above`

**Comment by meirion** [comment] 2020-07-06 17:26
Alright thanks for the explanation, I think I understand. From a novice user POV perhaps the type of thing you could say here could be "X photos skipped which already existed in Google Photos". In my opinion that wouldn't be a failure or error as such, but a notification or info type message.

I checked that photo URL and it says Uploaded by Android.

I must admit I was a bit lost trying to understand the choices you were discussing relating to either re-uploading existing photos or preserving album image order!

**Comment by ylexus** [comment] 2020-07-06 17:32
@

> Alright thanks for the explanation, I think I understand. From a novice user POV perhaps the type of thing you could say here could be "X photos skipped which already existed in Google Photos". In my opinion that wouldn't be a failure or error as such, but a notification or info type message.
Unfortunately, it's impossible to devise what the cause of this error is. All I get from Google Photos is the generic "INVALID_ARGUMENT" error, so assuming this error means exactly what you said above may confuse a user, if the actual cause is different.

> 
> I checked that photo URL and it says Uploaded by Android.
> 
> I must admit I was a bit lost trying to understand the choices you were discussing relating to either re-uploading existing photos or preserving album image order!
In order to understand this, you need to read through issue #49. In short, with current Google Photos API, Jiotty can either 
1. add pre-existing items, like your "Uploaded by Android" one above, to the new album OR
2. upload the items in such a way that they are ordered by date
, but not both (1) and (2). Currently, Jiotty is on setting (2). Issue #49 will allow the user to decide.

**Comment by meirion** [comment] 2020-07-06 17:36
OK I did a test, I edited the 4 images on my machine and cropped them so that they are visually different from the ones already uploaded.

I ran the upload again and it didn't show any errors this time.
However the new edited photos or the albums are neither appearing in Google Photos.

Latest from the log:

`2020-07-06T17:29:40,976 INFO [JavaFX Application Thread] n.y.g.c.CloudAlbumsProviderImpl Loading albums in cloud (may take several minutes)...
2020-07-06T17:29:40,976 INFO [ForkJoinPool.commonPool-worker-5] n.y.g.c.DirectoryStructureSupplierImpl Building album list from the file system...
2020-07-06T17:29:40,979 INFO [ForkJoinPool.commonPool-worker-5] n.y.g.c.DirectoryStructureSupplierImpl ... done, 4 directories found that will be used as albums
2020-07-06T17:29:41,026 DEBUG [upload-pool-0] n.y.j.c.g.p.GooglePhotosClientImpl List all albums
2020-07-06T17:29:43,852 DEBUG [upload-pool-0] n.y.j.c.g.p.PagedRequest Requesting list, page token [null]
2020-07-06T17:29:43,853 DEBUG [upload-pool-0] n.y.j.c.g.p.PagedRequest Received response to list request, page token [null], next page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhL3AkFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUttcHQwVS1hQXdoa2NKSHpsb3huaVozTVVuRXl2WklZUFpRRW5HTGdRa3BmY0NGTEdVTWtMcjczMkpmSk1CUzdDV3RadUZ2WWRMMWRlVVI4MzRKWS1MRUVId3A1S0NQM3Nwa2NvNmtxMTBjclNQUGh6ZFdRdmxxSW5QZ2ZtTTRIQ3NsOElfZ0pnTWZLY1lSNEVZWnNyWUFMRkhzVWozWnhRTDdtcjVaMFlqT3d6MkJfVDRYU3VwRURLZUNrendaazRxQUw4SVR5Wko5UlFaV3ZmMENUZkVwWjhxZ1NteEtQWl85Z2hucUpFMmlSM29SUy1Yb3BDTEtKRmh1MzJhck4wNmtYTnUzU2FJVjk2cWZIaE1vRjlmM2FDT0pOSkx6YlN4YmU1REhJZXl0TFhDM0psZWlRUmRfWG9IZUhaN0hYTjdQNHI4WRoA]
2020-07-06T17:29:45,700 DEBUG [upload-pool-0] n.y.j.c.g.p.PagedRequest Requesting list, page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhL3AkFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUttcHQwVS1hQXdoa2NKSHpsb3huaVozTVVuRXl2WklZUFpRRW5HTGdRa3BmY0NGTEdVTWtMcjczMkpmSk1CUzdDV3RadUZ2WWRMMWRlVVI4MzRKWS1MRUVId3A1S0NQM3Nwa2NvNmtxMTBjclNQUGh6ZFdRdmxxSW5QZ2ZtTTRIQ3NsOElfZ0pnTWZLY1lSNEVZWnNyWUFMRkhzVWozWnhRTDdtcjVaMFlqT3d6MkJfVDRYU3VwRURLZUNrendaazRxQUw4SVR5Wko5UlFaV3ZmMENUZkVwWjhxZ1NteEtQWl85Z2hucUpFMmlSM29SUy1Yb3BDTEtKRmh1MzJhck4wNmtYTnUzU2FJVjk2cWZIaE1vRjlmM2FDT0pOSkx6YlN4YmU1REhJZXl0TFhDM0psZWlRUmRfWG9IZUhaN0hYTjdQNHI4WRoA]
2020-07-06T17:29:45,701 DEBUG [upload-pool-0] n.y.j.c.g.p.PagedRequest Received response to list request, page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhL3AkFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUttcHQwVS1hQXdoa2NKSHpsb3huaVozTVVuRXl2WklZUFpRRW5HTGdRa3BmY0NGTEdVTWtMcjczMkpmSk1CUzdDV3RadUZ2WWRMMWRlVVI4MzRKWS1MRUVId3A1S0NQM3Nwa2NvNmtxMTBjclNQUGh6ZFdRdmxxSW5QZ2ZtTTRIQ3NsOElfZ0pnTWZLY1lSNEVZWnNyWUFMRkhzVWozWnhRTDdtcjVaMFlqT3d6MkJfVDRYU3VwRURLZUNrendaazRxQUw4SVR5Wko5UlFaV3ZmMENUZkVwWjhxZ1NteEtQWl85Z2hucUpFMmlSM29SUy1Yb3BDTEtKRmh1MzJhck4wNmtYTnUzU2FJVjk2cWZIaE1vRjlmM2FDT0pOSkx6YlN4YmU1REhJZXl0TFhDM0psZWlRUmRfWG9IZUhaN0hYTjdQNHI4WRoA], next page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhL3AkFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUtnNlNUOHJ5QkpHdzJsbkNVcV9BNDJSd2lwYy00a2h1d0toUlJHc2N1ZjJpdUxGY2NzVG04MmxGYmZvZUxQT1VCdTgxRVJhSEREc3lHeDlqVzd2cUJRSWktWDNBM2VhNUlCdmhQT05GWGEwYlh2Q2JhXzgzdG9oTm9QVmZ6RFl3TVVKZWpIYWNZMmdkVjFEWldYTkZuWjBEaXJnejk4SlVoRDY4TjJKNThiaHpXX3pibnluYzdwSVMtSGtWY01ES1ppQ0NwWkJJTkxiNWhKLWNWLU42VnNwZnRQOUI0cEFQVTJHSGw0YXNzTlVsRHpFWU5sc000Vk16ajRhdnhJVTRFcktjSjVxMFp6cFl2NHhoUWlCOFNRYnRlejJ5UlNOYXM4eFlOYzRiM2ZSZ0VIaWVoRUF0Sl84TkNUVm9qdDh4cnBWRlhWTRoA]
2020-07-06T17:29:49,273 DEBUG [upload-pool-0] n.y.j.c.g.p.PagedRequest Requesting list, page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhL3AkFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUtnNlNUOHJ5QkpHdzJsbkNVcV9BNDJSd2lwYy00a2h1d0toUlJHc2N1ZjJpdUxGY2NzVG04MmxGYmZvZUxQT1VCdTgxRVJhSEREc3lHeDlqVzd2cUJRSWktWDNBM2VhNUlCdmhQT05GWGEwYlh2Q2JhXzgzdG9oTm9QVmZ6RFl3TVVKZWpIYWNZMmdkVjFEWldYTkZuWjBEaXJnejk4SlVoRDY4TjJKNThiaHpXX3pibnluYzdwSVMtSGtWY01ES1ppQ0NwWkJJTkxiNWhKLWNWLU42VnNwZnRQOUI0cEFQVTJHSGw0YXNzTlVsRHpFWU5sc000Vk16ajRhdnhJVTRFcktjSjVxMFp6cFl2NHhoUWlCOFNRYnRlejJ5UlNOYXM4eFlOYzRiM2ZSZ0VIaWVoRUF0Sl84TkNUVm9qdDh4cnBWRlhWTRoA]
2020-07-06T17:29:49,273 DEBUG [upload-pool-0] n.y.j.c.g.p.PagedRequest Received response to list request, page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhL3AkFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUtnNlNUOHJ5QkpHdzJsbkNVcV9BNDJSd2lwYy00a2h1d0toUlJHc2N1ZjJpdUxGY2NzVG04MmxGYmZvZUxQT1VCdTgxRVJhSEREc3lHeDlqVzd2cUJRSWktWDNBM2VhNUlCdmhQT05GWGEwYlh2Q2JhXzgzdG9oTm9QVmZ6RFl3TVVKZWpIYWNZMmdkVjFEWldYTkZuWjBEaXJnejk4SlVoRDY4TjJKNThiaHpXX3pibnluYzdwSVMtSGtWY01ES1ppQ0NwWkJJTkxiNWhKLWNWLU42VnNwZnRQOUI0cEFQVTJHSGw0YXNzTlVsRHpFWU5sc000Vk16ajRhdnhJVTRFcktjSjVxMFp6cFl2NHhoUWlCOFNRYnRlejJ5UlNOYXM4eFlOYzRiM2ZSZ0VIaWVoRUF0Sl84TkNUVm9qdDh4cnBWRlhWTRoA], next page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhL3AkFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUt1Ni03NVVFRVh0RUZOYVh2Y2c5V3NnT3ZQblRrTnpfMHZrNUNYMXJVTllCaVF3WXg0bHNod1M2bTlGNXpiSkwxdTE2WUFnR0pJODBkRzMyZVhXZ3ZJSnZsX2RrWFBsaFVNYXg0b3duZnNDdHlLR3VhT3NZLVdxOU5weXFYRU5yNTU0THZGT3JTR3A2Mmx2VmxNUkRkM0lBeWthNVRuc3N6aUFFYnhNeDNFY0lYcGlWSE5ET1JpQnZRSnl3LW9LVW5mQkpOYXYzUEdEaUE3ellwRTJ6YmtKM2hUWXF6SFdiY2JvdTdGUGVsa3B1MlBfZnZjSjMtV1FBeUR1eWVPQnRRSlpHNE1sUVpFSEJsU2lfRExUMXo0M1R4bUhoVW5KMEFjTWJfcGFmaDI1NGFIUmtCZnVaekdDck5OZ3hCTlpydVRlcTFQVRoA]
2020-07-06T17:29:50,472 DEBUG [upload-pool-0] n.y.j.c.g.p.PagedRequest Requesting list, page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhL3AkFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUt1Ni03NVVFRVh0RUZOYVh2Y2c5V3NnT3ZQblRrTnpfMHZrNUNYMXJVTllCaVF3WXg0bHNod1M2bTlGNXpiSkwxdTE2WUFnR0pJODBkRzMyZVhXZ3ZJSnZsX2RrWFBsaFVNYXg0b3duZnNDdHlLR3VhT3NZLVdxOU5weXFYRU5yNTU0THZGT3JTR3A2Mmx2VmxNUkRkM0lBeWthNVRuc3N6aUFFYnhNeDNFY0lYcGlWSE5ET1JpQnZRSnl3LW9LVW5mQkpOYXYzUEdEaUE3ellwRTJ6YmtKM2hUWXF6SFdiY2JvdTdGUGVsa3B1MlBfZnZjSjMtV1FBeUR1eWVPQnRRSlpHNE1sUVpFSEJsU2lfRExUMXo0M1R4bUhoVW5KMEFjTWJfcGFmaDI1NGFIUmtCZnVaekdDck5OZ3hCTlpydVRlcTFQVRoA]
2020-07-06T17:29:50,473 DEBUG [upload-pool-0] n.y.j.c.g.p.PagedRequest Received response to list request, page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhL3AkFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUt1Ni03NVVFRVh0RUZOYVh2Y2c5V3NnT3ZQblRrTnpfMHZrNUNYMXJVTllCaVF3WXg0bHNod1M2bTlGNXpiSkwxdTE2WUFnR0pJODBkRzMyZVhXZ3ZJSnZsX2RrWFBsaFVNYXg0b3duZnNDdHlLR3VhT3NZLVdxOU5weXFYRU5yNTU0THZGT3JTR3A2Mmx2VmxNUkRkM0lBeWthNVRuc3N6aUFFYnhNeDNFY0lYcGlWSE5ET1JpQnZRSnl3LW9LVW5mQkpOYXYzUEdEaUE3ellwRTJ6YmtKM2hUWXF6SFdiY2JvdTdGUGVsa3B1MlBfZnZjSjMtV1FBeUR1eWVPQnRRSlpHNE1sUVpFSEJsU2lfRExUMXo0M1R4bUhoVW5KMEFjTWJfcGFmaDI1NGFIUmtCZnVaekdDck5OZ3hCTlpydVRlcTFQVRoA], next page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhLMAUFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUtwOExsYUo0NDVDM1ZTU2wtaWV0eEduN2w1MmQwdzhkOURmejNvVjU0cGtzS3JVejdRbktBb1ptQkJPZHhRMmFKVWdjVjNHOE9aOVQzRDR6TktNTU0xQnpsT2w1ckJ2UjVPVWpnSEZhaHlYcTNSZ1Uwb1FSUjRCT1FDdHZWUnJ5YUFkYmIzY2lUZ25WM2sxblQ0aFR0TEZ4MHRldhoA]
2020-07-06T17:29:51,615 DEBUG [upload-pool-0] n.y.j.c.g.p.PagedRequest Requesting list, page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhLMAUFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUtwOExsYUo0NDVDM1ZTU2wtaWV0eEduN2w1MmQwdzhkOURmejNvVjU0cGtzS3JVejdRbktBb1ptQkJPZHhRMmFKVWdjVjNHOE9aOVQzRDR6TktNTU0xQnpsT2w1ckJ2UjVPVWpnSEZhaHlYcTNSZ1Uwb1FSUjRCT1FDdHZWUnJ5YUFkYmIzY2lUZ25WM2sxblQ0aFR0TEZ4MHRldhoA]
2020-07-06T17:29:51,615 DEBUG [upload-pool-0] n.y.j.c.g.p.PagedRequest Received response to list request, page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhLMAUFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUtwOExsYUo0NDVDM1ZTU2wtaWV0eEduN2w1MmQwdzhkOURmejNvVjU0cGtzS3JVejdRbktBb1ptQkJPZHhRMmFKVWdjVjNHOE9aOVQzRDR6TktNTU0xQnpsT2w1ckJ2UjVPVWpnSEZhaHlYcTNSZ1Uwb1FSUjRCT1FDdHZWUnJ5YUFkYmIzY2lUZ25WM2sxblQ0aFR0TEZ4MHRldhoA], next page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhLMAUFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUtuUlBLQkVuRjZnMVVwbS1tTnZMaTBKSlE4aVRyRjJuSGotTGxqYURXeU8xdF9EUUFjUHZQRGdlaUlPSWFpM0hfTE5xR2VwMU1ZTjN2WWdWa1VHREMxTGg0d3NtMHg1MjZOZ3lZMndJZ0tfTkNBZjI2UkN4MXBndGdlT0JWcm1tekNIU3AwVHZNUkR1U0FCQWJaMmR5dnpILVlEeBoA]
2020-07-06T17:29:52,695 DEBUG [upload-pool-0] n.y.j.c.g.p.PagedRequest Requesting list, page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhLMAUFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUtuUlBLQkVuRjZnMVVwbS1tTnZMaTBKSlE4aVRyRjJuSGotTGxqYURXeU8xdF9EUUFjUHZQRGdlaUlPSWFpM0hfTE5xR2VwMU1ZTjN2WWdWa1VHREMxTGg0d3NtMHg1MjZOZ3lZMndJZ0tfTkNBZjI2UkN4MXBndGdlT0JWcm1tekNIU3AwVHZNUkR1U0FCQWJaMmR5dnpILVlEeBoA]
2020-07-06T17:29:52,695 DEBUG [upload-pool-0] n.y.j.c.g.p.PagedRequest Received response to list request, page token [CkQKPnR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnBob3Rvcy5saWJyYXJ5LnYxLkxpc3RBbGJ1bXNSZXF1ZXN0EgIIMhLMAUFIX3VRNDM4cG5VLW14XzFmVTUtMVU1UXk2LXhsM1FieXNJWU5ndm1teXVLajY0VUtuUlBLQkVuRjZnMVVwbS1tTnZMaTBKSlE4aVRyRjJuSGotTGxqYURXeU8xdF9EUUFjUHZQRGdlaUlPSWFpM0hfTE5xR2VwMU1ZTjN2WWdWa1VHREMxTGg0d3NtMHg1MjZOZ3lZMndJZ0tfTkNBZjI2UkN4MXBndGdlT0JWcm1tekNIU3AwVHZNUkR1U0FCQWJaMmR5dnpILVlEeBoA], next page token []
2020-07-06T17:29:52,696 DEBUG [upload-pool-0] n.y.j.c.g.p.GooglePhotosClientImpl Listed 278 album(s)
2020-07-06T17:29:52,696 INFO [upload-pool-0] n.y.g.c.CloudAlbumsProviderImpl ... loaded 278 album(s) in cloud
2020-07-06T17:29:52,699 INFO [upload-pool-0] n.y.g.c.AlbumManagerImpl Reconciling 3 albums(s) with Google Photos, may take a bit of time...
2020-07-06T17:29:52,844 INFO [upload-pool-0] n.y.g.c.GooglePhotosUploaderImpl Already uploaded, skipping: /Users/meirion.williams/Pictures/pics to sync/test folder 2/IMG_20200704_151559.jpg
2020-07-06T17:29:52,847 INFO [upload-pool-0] n.y.g.c.GooglePhotosUploaderImpl Already uploaded, skipping: /Users/meirion.williams/Pictures/pics to sync/test folder 1/test folder 1-1/IMG_20200704_185619.jpg
2020-07-06T17:29:52,847 DEBUG [state persistence - uploaded-items-0] n.y.g.c.UploadStateManagerImpl Saved state 1196215124 with 3 item(s)
2020-07-06T17:29:52,848 INFO [upload-pool-0] n.y.g.c.GooglePhotosUploaderImpl Already uploaded, skipping: /Users/meirion.williams/Pictures/pics to sync/test folder 1/IMG_20200704_145033.jpg
2020-07-06T17:29:52,849 INFO [upload-pool-0] n.y.g.c.UploaderImpl All done without errors, files uploaded: 4
`

**Comment by meirion** [comment] 2020-07-06 17:37
Sorry that's some pretty terrible formatting, don't know why that happened.

**Comment by meirion** [comment] 2020-07-06 17:40
Right, renamed all the photos and they all uploaded and the albums appeared - so it just needs unique filenames?

what happens if you've got dupe filenames in your collection? eg things like DSC0001.jpg etc?

**Comment by ylexus** [comment] 2020-07-06 17:47
Also see #49 

> Right, renamed all the photos and they all uploaded and the albums appeared 👍 - so it just needs unique filenames?

The reason Jiotty did not even attempt to upload them again was because you left the "resume from last attempt" checkbox on when trying again. It rightly did not attempt to upload the files that it already uploaded. It doesn't know you edited them. Although possible, I don't think I'll be supporting the file change detection yet.

> 
> what happens if you've got dupe filenames in your collection? eg things like DSC0001.jpg etc?

They will all be uploaded. There is no requirement for all file names to be unique.

**Comment by axylee** [comment] 2020-07-07 09:35
> @axylee can I please ask you to translate the following line in all Chinese resources, like before? Please leave %s placeholder - it will display the value of "progressBoxFailuresHyperlinkText" resource, for example, 错误:
> `uploadPaneLogAreaPartialSuccessLabel=Done with some failures, to review click on "%s" links above`

Sure , I am travel this few days , I will finished it by this week . So I just edit the files in "code " , to create a new branch , then pull request ? 

![image](https://user-images.githubusercontent.com/65884869/86760775-0e7e7b00-c078-11ea-9383-8a2496066c62.png)

**Comment by ylexus** [comment] 2020-07-08 20:57
@axylee yes, sounds right. Thanks for your help!

**Comment by ylexus** [comment] 2020-07-08 23:35
Fixed in 1.3.0

**Comment by ylexus** [comment] 2020-07-27 20:57
This one is pending Dutch translations, but will close as these depend on voluntary work by others and are not guaranteed.

**Closed by ylexus** 2020-07-27 20:57 UTC
Labels: good first issue
