### ISSUE TITLE
Problem with images missing "original date time" exif data

### ISSUE THREAD

**Issue by sefagurel** [ylexus/jiotty-photos-uploader#96] opened 2021-02-24 15:41 UTC
Hello, 

This app has saved my day. I just want to give information about a problem.

If "original date time" exif data is missing, it uploads with today's date. When I upload it to Google Photos via the web if there is no exif data, it uploads with the "last modification date" information.

Thank you.

**Comment by ylexus** [comment] 2021-02-24 15:49
What do you mean by "last modification date" here?

**Comment by sefagurel** [comment] 2021-02-24 15:56
if there is no exif information, google uses modified date data.

as an example the "modified" field in the picture

<img width="341" alt="Screen Shot 2021-02-24 at 18 51 34" src="https://user-images.githubusercontent.com/5000057/109026987-61717500-76d1-11eb-9134-bc0e8436c67e.png">

**Comment by ylexus** [comment] 2021-02-24 16:33
Unfortunately, this is limitation number 3 as documented here: https://github.com/ylexus/jiotty-photos-uploader/wiki#limitations.

**Comment by ylexus** [comment] 2021-02-24 16:34
Duplicate of #32.

**Closed by ylexus** 2021-02-24 16:34 UTC
