### ISSUE TITLE
Stock on Loading albums in cloud

### ISSUE THREAD

**Issue by Ampirooz** [ylexus/jiotty-photos-uploader#9] opened 2020-03-27 19:56 UTC
Stock on Loading albums in cloud
Changed IP, Not working
Uninstall and install, Not working
sign-out and signing , not working 
revoke access and grant it again, not working
![Screenshot (3)](https://user-images.githubusercontent.com/30123658/77795203-cae4a000-708a-11ea-8553-7200512f5dd6.png)

**Comment by ylexus** [comment] 2020-03-27 21:21
@Ampirooz, this looks like #6 which was fixed in 1.0.2 (the issue says it's only macOS, but it can affect Windows too). Can you ensure you are using the latest version, and if yes, then can you please zip and attach the logs from `%HOMEDRIVE%%HOMEPATH%\.jiottyphotosuploader\log` folder?

**Comment by Ampirooz** [comment] 2020-03-28 09:40
Thank you, issue solved with 1.0.2.
Great work btw..

**Comment by ylexus** [comment] 2020-03-28 12:12
@Ampirooz nice, thanks for reporting and enjoy! 
Closing as duplicate of #6.

**Comment by ylexus** [comment] 2020-03-28 12:12
Duplicate of #6

**Closed by ylexus** 2020-03-28 12:12 UTC
