### ISSUE TITLE
"INVALID_ARGUMENT: Request contains an invalid media item id." on existing photos.

### ISSUE THREAD

**Issue by jaytohe** [ylexus/jiotty-photos-uploader#49] opened 2020-06-28 13:55 UTC
Hi and thanks for this great app! It definitely saves me from a lot of trouble. As per the wiki you've written and specifically "If a photo has already been uploaded, will duplicate be created?"--->3, the program should be able to add photos already exist in Google Photos AND that are uploaded again to an album created by Jiotty. 

I can't get this to work however and Jiotty spits out an "INVALID_ARGUMENT: Request contains an invalid media item id" error. I even tried with one photo to no avail. Clearing out the .jiottyphotouploader folder also didn't help.

What gives?

**Comment by ylexus** [comment] 2020-06-28 16:03
@jaytohe, I've reproduced this. Oh the joys of Google Photos API. This is what's happening. There are two ways you can get a media item into an album.
1. When creating the item using [batchCreate](https://developers.google.com/photos/library/reference/rest/v1/mediaItems/batchCreate), you can specify the album ID. In this case, even if the item was already uploaded via the web interface before, it gets successfully added to the album.
2. Create an item with [batchCreate](https://developers.google.com/photos/library/reference/rest/v1/mediaItems/batchCreate) **without** specifying the album, and then use [batchAddMediaItems](https://developers.google.com/photos/library/reference/rest/v1/albums/batchAddMediaItems) to add items to the album. In this case, if the item was uploaded via the web interface before, it fails with the problem you reported:
```json
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid media item id.",
    "status": "INVALID_ARGUMENT"
  }
}
```

I'd say it's a bug in Google Photos API as the error is too generic and it clearly works one way and doesn't work another.

I switched from method (1) to method (2) as part of solving issue #31, which introduced this regression. It's really a shame, as we can either have the correct order of items in the album or the ability to add pre-existing items to albums created by Jiotty. To fix it transparently I'll have to dynamically attempt one way and, if it fails, try another, or come up with some cleverer solution. In any case, it's not a simple fix.

As  a workaround I suggest you download and use version [1.0.9](https://github.com/ylexus/jiotty-photos-uploader/releases/tag/1.0.9) which is before I fixed #31. It should do what it says in the wiki.

I'll update the wiki to mention this issue.

**Comment by ylexus** [comment] 2020-06-28 16:12
Relevant Google Photos API issues:
1. https://issuetracker.google.com/u/7/issues/134100429
2. https://issuetracker.google.com/issues/132274769

**Comment by ylexus** [comment] 2020-06-28 17:17
@jaytohe if you do try 1.0.9 then your items won't be sorted by creation date in albums, obviously. At the moment it's a trade-off, I can't see how I can make both work at the same time.

**Comment by jaytohe** [comment] 2020-06-28 17:22
Hi and thanks for your prompt response! I used the workaround (ver. 1.0.9) and it did the trick! I actually don't care that the items aren't sorted by creation date since the images were mostly memes lol. Thanks again.

**Comment by jaytohe** [comment] 2020-06-28 17:45
If I understand correctly, in order for the media uploaded to be correctly sorted by date, you re-arrange them based on their date of creation before making the API request and Google won't mess with that order sent,correct? What I don't understand is why not use the old way (method 1) and then to sort it, the user just has to click edit album from the app and then sort by--> oldest first? Will this not work?

**Comment by ylexus** [comment] 2020-06-28 19:13
The problem is, I can’t re-arrange them before I upload, as finding out the “date taken” from a media is a complex thing. So I first upload, GP returns me metadata of each item, including “date taken”, I sort by that date and then issue the add to album request. More information on this issue is in #31. 

As for using approach (1) and let user sort the items manually, one problem with it is that this is a mass upload tool. In my case, I had nearly a 1000 of albums. Manually going through each is an impossible ask. 

However, in my case I also did not care about the order of items in albums, but I did care about pre-existed items added to correct albums. 

So one option here, which is quite easy to do, is to let user decide. A simple toggle on the directory chooser screen would do: “do you want to auto-organise by date or do you value the ability to add pre-existing photos to albums”? @wheleph, what do you think here?

**Comment by wheleph** [comment] 2020-07-02 11:10
@ylexus the toggle will certainly be confusing to users but I understand that it's the best we can have for the time being. I'd suggest to keep the old behavior (possibility to add existing media items) as a default since it will lead to less scary errors shown to users. But if someone (like me) prefers to have the other behaviour then their choice should be persisted between invocation of the application.

**Comment by ylexus** [comment] 2020-07-08 23:29
OK this is done. @axylee there are also phrases to be translated for this issue too (added quite  bit of text). Maybe you could do the ones for #50 and this one together when you're back from your travels.

**Comment by ylexus** [comment] 2020-07-08 23:35
Fixed in 1.3.0, Chinese/Dutch translation pending in 1.3.1

**Comment by axylee** [comment] 2020-07-09 10:01
> OK this is done. @axylee there are also phrases to be translated for this issue too (added quite bit of text). Maybe you could do the ones for #50 and this one together when you're back from your travels.

I don't quite understand this 
![image](https://user-images.githubusercontent.com/65884869/87026256-11ab6f80-c20e-11ea-83b5-4ad53022d6a3.png)

Does this conflict with this ?
![image](https://user-images.githubusercontent.com/65884869/87026326-2c7de400-c20e-11ea-80ec-2927577795fa.png)

**Comment by ylexus** [comment] 2020-07-09 10:03
> > OK this is done. @axylee there are also phrases to be translated for this issue too (added quite bit of text). Maybe you could do the ones for #50 and this one together when you're back from your travels.
> 
> 
> 
> I don't quite understand this 
> 
> ![image](https://user-images.githubusercontent.com/65884869/87026256-11ab6f80-c20e-11ea-83b5-4ad53022d6a3.png)
> 
> 
> 
> Does this conflict with this ?
> 
> ![image](https://user-images.githubusercontent.com/65884869/87026326-2c7de400-c20e-11ea-80ec-2927577795fa.png)
> 
> 
> 
> 

Yes it does, thanks for noticing. Please ignore the wiki - I’ll need to update it.

**Closed** 2020-07-27 20:57 UTC
